server:
  host: "0.0.0.0"
  port: 5001
  max_size: 8 # Calculate by megabyte
  valid_token: "VALID_TOKEN"
database:
  host: "115.165.166.55"
  port: 1521
  user: "jira"
  password: "MyGIAgVwrzQRj8lhD54k"
  sn: "COREDB"
